### ISSUE TITLE
Create a tag release 1.0

### ISSUE THREAD

**Issue by gvollant** [neosmart/pevents#23]
Hello,
I'm a former C/C++ Windows NT only programmer (1993 until 2007) and now I support both Windows and Posix 

So your library is very helpful to port my code to posix multihread. Thank you. It's a very clean and professional code.

I suggest you create a "1.0" tag on github (and update sometime). This help inclusion on professional package

Thank you !

**Comment by mqudsi** [comment]
Hello @gvollant.

Thanks for your kind words and for being a long-time supporter of this project. Per your suggestion, [I have just released pevents 1.22.11](https://github.com/neosmart/pevents/releases/tag/1.22.11).

I hope you keep well!
