### ISSUE TITLE
pthread_mutex_lock deadlock in ResetEvent() and WaitForEvent() under Android when abi is arm64-v8a 

### ISSUE THREAD

**Issue by santoxyz** [neosmart/pevents#6]
I'm experiencing deadlocks compiling the library under android, when using arm64-v8a ABI.
With armeabi-v7a everything looks fine.

**Comment by mqudsi** [comment]
Hello santoxyz,

Do you have a specific test suite or repro?

**Comment by mqudsi** [comment]
I'm able to run the sample fine without any deadlocks under 64-bit ARMv8-A (aarch64), compiled with llvm 8.0.1 out of the git repo.
